config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :users, only: [:new, :create, :index, :show]
  resources :time_counts, only: [:new, :create, :show]

  get 'workers/track_user', to: 'users#track_user', as: :track_user
  get 'see_log', to: 'time_counts#see_log', as: :see_log
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_count.rb
class TimeCount < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :time_counts

  after_create :generate_tracker_id

  validates :name, presence: true
  validates :date_of_birth, presence: true

  private

  def generate_tracker_id
    tracker_id = rand(10000..10000000).to_s
    self.update(tracker_id: "#{tracker_id}_#{self.id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/time_counts_controller.rb
class TimeCountsController < ApplicationController

  before_action :check_session

  def new
    if @is_active
      @user = User.find_by(tracker_id: session[:tracker_id])
      @time_count = @user.time_counts.last
      @total_time_worked = @time_count.user.time_counts.sum(:total_time)
    end
  end

  def create
    @user = User.find_by(tracker_id: params[:tracker_id])
    if @user.present?
      if params[:commit] === 'Punch In'
        @time_count = @user.time_counts.new
        @time_count.punch_in_time = DateTime.now
        @time_count.active = true
        if @time_count.save
          session[:tracker_id] = params[:tracker_id]
          redirect_to new_time_count_path, notice: 'Time tracking has been started.'
        else
          render :new
        end
      elsif params[:commit] === 'Punch Out'
        @time_count = @user.time_counts.last
        total_time = ((DateTime.now - @time_count.punch_in_time.to_datetime) * 24 * 60 * 60).to_i
        if @time_count.update(punch_out_time: DateTime.now, total_time: total_time, active: false)
          session.delete(:tracker_id)
          redirect_to new_time_count_path, notice: 'Time tracking has been ended.'
        else
          render :new
        end
      elsif params[:commit] === 'See Log'
        redirect_to time_count_path(@user.time_counts.last)
      end
    else
      redirect_to new_time_count_path, alert: 'Worker not found!!'
    end
  end

  def show
    @time_count = TimeCount.find(params[:id])
    @total_time_worked = @time_count.user.time_counts.sum(:total_time)
  end

  def see_log
  end

  private

  def time_count_params
    params.permit(:tracker_id)
  end

  def check_session
    if session[:tracker_id].present?
      @is_active = true
    else
      @is_active = false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user), notice: 'Registration Complete.'
    else
      render :new
    end
  end

  def show
  end

  def track_user
    user = User.find_by(tracker_id: params[:tracker_id])
    if user.present?
      time_count = user.time_counts.find_by(active: true)
      if time_count.present?
        render json: { success: true }
      else
        render json: { success: false }
      end
    else
      render json: { success: false }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def converted_time(dif)
    Time.at(dif).utc.strftime("%H Hours %M Minutes")
  end

  def full_date(datetime)
    datetime.strftime('%d %B, %Y')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/time_counts_helper.rb
module TimeCountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div style="text-align: center; font-size: 32px;">
  <h1>TimeClock: Track Your Time Easily</h1>
</div>

app/views/layouts/_error_message.html.erb
<div class="container-fluid" id="error_msg">
  <% if object.errors.full_messages.any? %>
    <% object.errors.full_messages.each do |error_message| %>
      <p class="alert alert-danger"> <%= error_message if object.errors.full_messages.first == error_message %> </p>
    <% break end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeClock</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= controller_name %> <%= action_name %>">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "TimeClock", root_path, class: "navbar-brand", id: 'hero_text' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/users/new">Register <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Timeclock', new_time_count_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Audit', users_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'See Your Log', see_log_path, class: 'nav-link'%>
      </li>
    </ul>
  </div>
</nav>
<div class="container-fluid" id="flash_msg">
  <% flash.each do |key, value| %>
    <% if key == "alert" %>
      <%= content_tag(:div, value, class: "alert alert-danger") %>
    <% elsif key == "notice" %>
      <%= content_tag(:div, value, class: "alert alert-success") %>
    <% end %>
  <% end %>
</div>
<div class="container" id="main-div">
  <%= yield %>
</div>
</body>
</html>

app/views/time_counts/new.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-6">
        <%= form_with url: time_counts_path, method: :post do |form| %>
          <div class="form-group">
            <%= form.label 'Tracker ID', class: 'control-label' %>
            <% if @is_active %>
              <%= form.text_field :tracker_id, value: session[:tracker_id], class: 'form-control', id: 'tracker_id' %>
            <% else %>
              <%= form.text_field :tracker_id, class: 'form-control', id: 'tracker_id' %>
            <% end %>
          </div>
          <div class="form-group">
            <% if @is_active %>
              <%= form.submit 'Punch Out', class: 'btn btn-success', id: 'punch_button' %>
            <% else %>
              <%= form.submit 'Punch In', class: 'btn btn-success', id: 'punch_button' %>
            <% end %>
            <%= link_to 'Back', root_path, class: 'btn btn-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if @is_active %>
    <div class="card-body">
      <div class="col-12">
        <h5>Your current logged time is
          <strong><%= converted_time(((DateTime.now - @time_count.punch_in_time.to_datetime) * 24 * 60 * 60).to_i) %></strong>
        </h5>
        <h5>Your have been logged in for <strong><%= converted_time(@total_time_worked) %></strong> in total.</h5>
      </div>
    </div>
  <% end %>
</div>

app/views/time_counts/see_log.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-6">
        <%= form_with url: time_counts_path, method: :post do |form| %>
          <div class="form-group">
            <%= form.label 'Tracker ID', class: 'control-label' %>
            <%= form.text_field :tracker_id, class: 'form-control', id: 'tracker_id' %>
          </div>
          <div class="form-group">
            <%= form.submit 'See Log', class: 'btn btn-success', id: 'log_button' %>
            <%= link_to 'Back', root_path, class: 'btn btn-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/time_counts/show.html.erb
<div class="card">
  <div class="card-header">
    <h1>Hello <%= @time_count.user.name %></h1>
    <% if @time_count.active %>
      <h3>Your current logged time is <%= converted_time(((DateTime.now - @time_count.punch_in_time.to_datetime) * 24 * 60 * 60).to_i) %>.</h3>
      <h3>Your have been logged in for <%= converted_time(@total_time_worked) %> in total.</h3>
  <% else %>
      <h3>Your were logged in for <%= converted_time(@total_time_worked) %> in total.</h3>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render partial: 'layouts/error_message', locals: {object: @user} %>
  <div class="form-group">
    <%= form.label :name, class: 'control-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth, class: 'control-label' %>
    <%= form.date_field :date_of_birth, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.submit 'Register', class: 'btn btn-success' %>
    <%= link_to 'Back', root_path, class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Workers</h1>

<table class="table table-bordered" id="workers_list_table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Date of Birth</th>
    <th>ID</th>
    <th>Total Time</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= full_date(user.date_of_birth) %></td>
      <td><%= user.tracker_id %></td>
      <% if user.time_counts.count > 0 %>
        <td><%= converted_time(user.time_counts.sum(:total_time)) %></td>
          <% if user.time_counts.last.active %>
          <td class="active-status">
            Active
          </td>
          <% else %>
          <td class="inactive-status">
            Inactive
          </td>
          <% end %>
      <% else %>
        <td>No Record</td>
        <td class="inactive-status">Inactive</td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= link_to "Back", root_path, class: "btn btn-dark" %>
</div>

app/views/users/new.html.erb
<div class="card">
  <div class="card-header">
    <h3>Create Profile</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-6">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-header">
    <h2>Your time tracking ID is: <%= @user.tracker_id %></h2>
    <h4>Use it to track your time.</h4>
  </div>
</div>